#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH="$PATH":~/.local/bin

#export PATH=$HOME/.fnm:$PATH
#eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# FZF
# shows hidden files
# export FZF_CTRL_T_COMMAND='ag --hidden --ignore .git -g ""'
# shows hidden files and ignores node_modules and .git
export FZF_CTRL_T_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!{**/node_modules/*,**/.git/*}'"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#        . "$HOME/.miniconda/etc/profile.d/conda.sh"
#    else
#        export PATH="$HOME/.miniconda/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

# cuda
export PATH="/usr/local/cuda-11.5/bin"${PATH:+:"${PATH}"}""
export LD_LIBRARY_PATH="/usr/local/cuda-11.5/lib64\
    "${LD_LIBRARY_PATH:+:"${LD_LIBRARY_PATH}"}""
export CUDACXX=/usr/local/cuda/bin/nvcc
export CUDA_HOME=/usr/local/cuda

