#!/bin/sh

# functions
function mcd() {
    mkdir -p "$1"
    cd "$1"
}
function tvim() {
    touch "$1"
    nvim "$1"
}
function extract() {
    cp -a "$1"/. .
    rm -r "$1"
}
function cf() {
    # check if .clang-format already exists
    if [ -z "$1" ]
    then
        default="Microsoft"
        cfConfigPath="$HOME/.config/nvim/config/.clang-format"
        if [ -e "$cfConfigPath" ]
        then
            cp $cfConfigPath ./.clang-format
            if [ $? -eq 0 ]; then; printf "The default .clang-format file was copied.\n"; fi
        else
            clang-format -style=$default -dump-config > .clang-format
            if [ $? -eq 0 ]; then; printf "Created a .clang-format file using $default style.\n"; fi
        fi
    else
        clang-format -style=$1 -dump-config > .clang-format
        if [ $? -eq 0 ]; then; printf "Created a .clang-format file using $1 style.\n"; fi
    fi
}

# tmux in 256 colors
# alias tmux='TERM=xterm-256color tmux'
alias tmux='tmux -2'

# tree to ignore files
alias tree='rg --files | tree --fromfile'

# alias commit='source ~/git-scripts/commit.sh'
alias scommit='source ~/git-scripts/commit-silent.sh'
alias pull='source ~/git-scripts/pull.sh'
alias spull='source ~/git-scripts/pull-silent.sh'
alias pyvenv='source ~/virtualenv-creator/src/Bash/pyvenv.sh'
alias make16='make -j16'
alias notes='nvim ~/notes/notes.txt'
alias ll='ls -alF --color=auto'
alias ls='ls -a --color=auto'
alias rtmux='tmux source-file ~/.tmux.conf'
alias aptdate='sudo apt update; sudo apt -y upgrade; sudo apt-get -y update'
alias prev='$_'
# alias j='z'
# alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# trash-cli
alias tp='trash-put'
alias tl='trash-list'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
#alias cp="cp -i"
#alias mv='mv -i'
#alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# git branches
alias bm="git checkout master"
alias bs="git checkout stable"
alias bf="git checkout feature"
alias bt="git checkout test"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
