#!/bin/sh
mcd() {
    mkdir -p "$1"
    cd "$1"
}
tvim() {
    touch "$1"
    nvim "$1"
}
# alias tmux='TERM=xterm-256color tmux'
alias tmux='tmux -2'
alias tree='rg --files | tree --fromfile'
# export PATH="$PATH":~/Git/git-commit/build/commit
# alias commit='source ~/Git/git-commit-kit/commit.sh'
alias pyvenv='source ~/virtualenv-creator/src/Bash/pyvenv.sh'
alias make16='make -j16'
alias notes='nvim ~/notes/notes.md'
alias ll='ls -alF'
alias ls='ls -a'
alias tmuxr='tmux source-file ~/.tmux.conf'
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
# trash-cli
alias tp='trash-put'
alias tl='trash-list'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
#alias cp="cp -i"
#alias mv='mv -i'
#alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# git branches
alias bm="git checkout master"
alias bs="git checkout stable"
alias bf="git checkout feature"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
