#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH=$HOME/.local/bin:$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# sumneko_lua language server
export PATH=$HOME/lsp/lua-language-server/bin:$PATH

#export PATH=$HOME/.fnm:$PATH
#eval "$(fnm env)"
eval "$(zoxide init zsh)"

# FZF
# shows hidden files and ignores node_modules and .git
export FZF_DEFAULT_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!{**/node_modules/*,**/.git/*}'"
export FZF_CTRL_T_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!{**/node_modules/*,**/.git/*}'"
# export FZF_DEFAULT_OPTS='--height 95% --reverse --preview "cat {}"'
export FZF_DEFAULT_OPTS='--reverse --preview "cat {}"'

# cuda
export PATH="/usr/local/cuda-11.5/bin"${PATH:+:"${PATH}"}""
export LD_LIBRARY_PATH="/usr/local/cuda-11.5/lib64\
    "${LD_LIBRARY_PATH:+:"${LD_LIBRARY_PATH}"}""
export CUDACXX=/usr/local/cuda/bin/nvcc
export CUDA_HOME=/usr/local/cuda

