#!/bin/sh

# FUNCTIONS:
function mcd() { mkdir -p "$1"; cd "$1" }
function tvim() { touch "$1"; nvim "$1" }
function extract() { cp -a "$1"/. .; rm -r "$1" }

function format() {
    if [ -z "$1" ]; then
        printf "Use one of the following languages as an argument:\ncpp, lua\n"
    else
        if [ "$1" = "cpp" ]; then; formatter='.clang-format'
        elif [ "$1" = "lua" ]; then; formatter='.stylua.toml'
        else
            printf "Error: Not a valid argument.\n"
            exit 1
        fi
        if ! [ -e "./$formatter" ]; then
            configPath="$HOME/.config/nvim/formatters/$formatter"
            cp $configPath ./$formatter
            printf "The formatter config file '$formatter' was created.\n"
        else
            printf "Error: The formatter config file '$formatter' already exists here.\n"
            exit 1
        fi
        exit 0
    fi
}


# ALIASES:
# tmux in 256 colors
alias tmux='tmux -2'

# tree to ignore files
alias tree='rg --files | tree --fromfile'

# cmake
alias vg="valgrind --leak-check=full --show-leak-kinds=all \
    --track-origins=yes --verbose --log-file=valgrind-out.txt "
alias dmake='cmake -DCMAKE_BUILD_TYPE=Debug'

alias commit='source ~/git-scripts/commit.sh'
alias scommit='source ~/git-scripts/commit-silent.sh'
alias pull='source ~/git-scripts/pull.sh'
alias spull='source ~/git-scripts/pull-silent.sh'
alias pyvenv='source ~/virtualenv-creator/src/Bash/pyvenv.sh'
# alias make='make -j16'
alias ll='ls -alF --color=auto'
alias ls='ls -a --color=auto'
alias rtmux='tmux source-file ~/.tmux.conf'
alias aptdate='sudo apt update; sudo apt -y upgrade; sudo apt-get -y update'
alias git clone='git clone --recursive'
# alias lg='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# trash-cli
alias tp='trash-put'
alias tl='trash-list'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
#alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# git branches
alias bm="git checkout master"
alias bs="git checkout stable"
alias bf="git checkout feature"
alias bt="git checkout test"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
