set -s extended-keys on
set -s focus-events on

set -g mouse on
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Ghostty's command+[ equivalent
bind O select-pane -t :.-

# Open new panes at the current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
